-- INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (1, 'ADMIN');
-- INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (2, 'USER');
--
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
--
--
